# Nome do seu fluxo de trabalho
name: CI/CD

# Gatilhos que acionam o fluxo de trabalho
on:
  pull_request:
    branches:
      - Dev
      - Test
      - Prod
  push:
    branches:
      - Test

# Definição dos trabalhos (jobs) no seu fluxo de trabalho
jobs:
  # Job para construir o código
  build:
    runs-on: ubuntu-latest  # Define a plataforma na qual o job será executado

    steps:
      - name: Checkout code  # Passo para obter o código do repositório
        uses: actions/checkout@v2

      - name: Set up Python  # Passo para configurar a versão do Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

  # Job para executar os testes
  test:
    runs-on: ubuntu-latest

    needs: build  # Indica que este job depende do job 'build' ser concluído

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run unit tests
        run: python -m unittest discover

  # Job para aprovar na branch Dev
  approve-dev:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Add 'approved' label
        run: |
          echo "label: approved" >> $GITHUB_EVENT_PATH

  # Job para aprovar na branch Test
  approve-test:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Add 'approved' label
        run: |
          echo "label: approved" >> $GITHUB_EVENT_PATH

  # Job para construir o artefato
  build-artifact:
    runs-on: ubuntu-latest

    permissions: write-all

    needs: 
      - approve-dev
      - approve-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: Build artifact
        run: pyinstaller --onefile task_manager_gui.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: task_manager_gui  # Nome do artefato
          path: ./dist/task_manager_gui  # Caminho para o diretório do artefato
